# Generated by Django 5.2.12 on 2026-03-17 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('avg_reaction_ms', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('exercise', models.CharField(default='gridshot', max_length=50)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discorduser')),
            ],
        ),
    ]
