# Generated by Django 5.2.12 on 2026-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_on_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tracking_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='avg_reaction_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.CharField(choices=[('gridshot', 'Gridshot'), ('tracking', 'Tracking'), ('flicking', 'Flicking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
