# Generated by Django 5.2.12 on 2026-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_time_on_target_session_tracking_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='misses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.CharField(choices=[('flicking', 'Flicking'), ('tracking', 'Tracking'), ('precision', 'Precision')], max_length=50),
        ),
    ]
