# Generated by Django 5.2.12 on 2026-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_difficulty_session_misses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
