# Generated by Django 5.2.12 on 2026-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
